# Generated by Django 6.0.5 on 2026-05-11 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(28)])),
                ('course_name', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_name', models.CharField(choices=[('it', 'It'), ('cs', 'Cs'), ('is', 'Is')], max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['enrolled_at'],
            },
        ),
    ]
